services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-user:/var/lib/postgresql/data
      - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    image: go-postgres-grpc-user-dir:${IMAGE_VERSION}
    build: .
    ports:
      - "${SRV_PORT_USER}:${SRV_PORT_USER}"
    entrypoint: /bin/sh
    command: /start.sh

volumes:
  db-user:
